### PR TITLE
Allow non-source directory builds

### PR DESCRIPTION
**Pull request by pothos**
Similar to https://github.com/storaged-project/libblockdev/pull/252 this needs to be changed in order to build with e.g. jhbuild. The point is also to invoke ./configure from ./autogen.sh.

### CODE REVIEW

**Comment by vpodzime** [comment]
> The point is also to invoke ./configure from ./autogen.sh.

I don't really want this being done.

**Comment by vpodzime** [comment]
What is the real purpose of this? IOW, what does *jhbuild* do? ``make distcheck`` passes just fine so it looks to me like *jhbuild* does something really weird.

**Comment by pothos** [comment]
I'll look for a way to have ./autogen.sh not call ./configure – the main difference I see is that cwd is the builddir in jhbuild and the current autogen.sh is expecting it to be also the srcdir.

**Comment by vpodzime** [comment]
> the main difference I see is that cwd is the builddir in jhbuild and the current autogen.sh is expecting it to be also the srcdir

I'm sorry, but I'm still not following here. Why is *jhbuild* running ``autogen.sh``? Every build system is supposed to take a tarball and then run ``./configure && make && make install`` with some options.

**Comment by pothos** [comment]
I see, makes sense somehow - but since configure is not in master that would make a development build more difficult.

**Comment by ebassi** [comment]
@vpodzime "Every build system is supposed to take a tarball" — this is an invalid assumption.

Build systems can (and should) build from Git, like [GNOME Continuous](https://build.gnome.org) which is tasked to do continuous integration and delivery; or like JHBuild, which is used for development. Only Linux distro packages build from tarball, and it's still a questionable relic of a bygone era.

The autogen.sh script should be allowed to run both in the srcdir, and in the target builddir; since Autotools is broken by design and creates files into the srcdir, the autogen.sh script must be resilient to that. The autogen.sh can also call the generated configure script, but if it does that it must allow disabling this behaviour, via an environment variable.

I strongly suggest reading the [build API](https://github.com/cgwalters/build-api) which attempts at describing the subset of Autotools best practices that projects should implement in their build system to allow build environments to work without necessarily adding ad hoc exception for each project.

**Comment by ebassi** [comment]
Incidentally, this PR is correct, and adheres to the build API.

**Comment by pothos** [comment]
If wanted I can remove calling ./configure from the PR as this would be still ok for jhbuild and continuous.

**Comment by vpodzime** [comment]
> If wanted I can remove calling ./configure from the PR as this would be still ok for jhbuild and continuous.

Yes, please do that.

**Comment by pothos** [comment]
Hm, was not able to have jhbuild calling configure afterwards - I don't know why and this is only related to my case (env does not contain NOCONFIGURE).

**Comment by pothos** [comment]
And also this here fails (but I was able to build somehow before…)
```
libbytesize/translation-canary/xgettext_werror.sh --keyword=_ --keyword=N_ --keyword=P_:1,2 --keyword=C_:1c,2 --keyword=CN_:1c,2 --keyword=CP_:1c,2,3 --add-comments=TRANSLATORS: --from-code=UTF-8 --package-name=libbytesize --package-version=0.10 --copyright-holder="Red Hat, Inc." --msgid-bugs-address="anaconda-devel-list@redhat.com" --directory=/home/kai/jhbuild/checkout/libbytesize -o libbytesize.pot \
    
xgettext: no input file given
```

**Comment by pothos** [comment]
Okay, so it works with supports-non-srcdir-builds="no" in the jhbuild modulesets, so to get to the purpose of the PR this xgettext issue would also need to be solved.

**Comment by pothos** [comment]
The xgettext path isse seems to be fixed, but because of removing the ./configure invokation this depends on a patch in jhbuild:
https://bugzilla.gnome.org/show_bug.cgi?id=741052

**Comment by pothos** [comment]
It's directly usable in jhbuild with an additional specification:
`autogen-template="%(srcdir)s/%(autogen-sh)s &amp;&amp; %(srcdir)s/configure --prefix=%(prefix)s %(autogenargs)s"`

**Comment by vpodzime** [comment]
Jenkins, this is ok to test.

**Pull request merged**
