### PR TITLE
Add support to ppc64le for debian build

### PR DESCRIPTION
**Pull request by gururajrkatti**
This PR adds CI support for the IBM Power Little Endian (ppc64le) architecture. The idea is to ensure that the builds on this architecture are continuously tested along with the Intel builds (amd64) as this is part of the ubuntu distro on that architecture as well and detecting (and fixing) any issues or failures early would help to ensure that we are always up to date.

### CODE REVIEW

**Comment by StorageGhoul** [comment]
Can one of the admins verify this patch?

**Review by vojtechtrefny — CHANGES_REQUESTED** [review]
Thank you, looks good to me. Can you please remove the merge commit from the PR?

**Comment by gururajrkatti** [comment]
@vojtechtrefny thanks for the feedback. It's showing up the merge commit just because I wanted to keep my branch in sync with the master. It should not affect this PR in anyway. Let me know if it is okay. Or else I have to delete my branch totally and create fresh one and create new PR

**Comment by gururajrkatti** [comment]
@vojtechtrefny thanks for the feedback. It's showing up the merge commit just because I wanted to keep my branch in sync with the master. It should not affect this PR in anyway. Let me know if it is okay. Or else I have to delete my branch totally and create fresh one and create new PR

**Comment by vojtechtrefny** [comment]
[Merged manually](https://github.com/storaged-project/libbytesize/commit/91d52224271ed5707627db126692c38ceb4b88bf). Thank you.

**Comment by gururajrkatti** [comment]
Thanks !

**Pull request closed without merging**
