### PR TITLE
Preparations for migration to Weblate

### PR DESCRIPTION
**Pull request by vojtechtrefny**
See https://github.com/storaged-project/libbytesize/issues/63

### CODE REVIEW

**Comment by Jibec** [comment]
thank your for starting this, please remove every po files with no translations progress.
for example, you can detect them with pocount (from language toolkit)

**Comment by Jibec** [comment]
it's a good thing you don't wait for release to generate pot file, but when will you update it in the new process?

**Comment by vojtechtrefny** [comment]
> thank your for starting this, please remove every po files with no translations progress.

Good point, I have removed PO files with no translations.

> it's a good thing you don't wait for release to generate pot file, but when will you update it in the new process?

Still during the release process, just only once instead of twice. I know it's bad to push new pot file only after the release but this shouldn't be a problem for libbytesize -- we haven't changed the translatable strings since the initial release and we don't plan to add new features. If we ever change some strings we'll need to remember to update the pot file manually.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Pull request merged**
